### ISSUE TITLE
Makefile isn't idiot-proof

### ISSUE THREAD

**Issue by ghost** [Percona-Lab/mysql_random_data_load#12]
Hi Percona guys,

Seems dumb but I've run _**make**_ as root in amazon linux 2017, /bin deleted as result, It was a test vm. But ...

Thanks in advance!

**Comment by percona-csalguero** [comment]
Updated: https://github.com/Percona-Lab/mysql_random_data_load/commit/b91fccd3c62e502aea772391abb43d117297e4ec
