### ISSUE TITLE
panic: invalid argument to Int63n

### ISSUE THREAD

**Issue by rbustos** [Percona-Lab/mysql_random_data_load#24]
Anyone having same issue?

(Centos 7 x64)

./mysql_random_data_load test test 10 --bulk-size=1 -h 127.0.0.1 --max-threads=1 --print -u root -p test
**panic: invalid argument to Int63n**

goroutine 1 [running]:a
math/rand.(*Rand).Int63n(0xc00008e180, 0x8000000000000000, 0x3fc408d2ac22c4d3)
	/usr/local/go/src/math/rand/rand.go:111 +0x10d
math/rand.Int63n(0x8000000000000000, 0x16d)
	/usr/local/go/src/math/rand/rand.go:319 +0x37
github.com/Percona-Lab/mysql_random_data_load/internal/getters.(*RandomDecimal).Value(0xc0001f6440, 0xc0002fe000, 0xc0002fe15a)
	/home/karl/go/src/github.com/Percona-Lab/mysql_random_data_load/internal/getters/decimal.go:17 +0x85
github.com/Percona-Lab/mysql_random_data_load/internal/getters.(*RandomDecimal).String(0xc0001f6440, 0xc0002fe000, 0x16d)
	/home/karl/go/src/github.com/Percona-Lab/mysql_random_data_load/internal/getters/decimal.go:22 +0x2f
github.com/Percona-Lab/mysql_random_data_load/internal/getters.(*RandomDecimal).Quote(0xc0001f6440, 0xc0000b66e0, 0x158)
	/home/karl/go/src/github.com/Percona-Lab/mysql_random_data_load/internal/getters/decimal.go:26 +0x2b
main.run(0xc0001220c0, 0xc000114480, 0xc000114700, 0xc00006c0e0, 0xc0002d2000, 0x1c, 0x20, 0xa, 0x1, 0xc00005b8c0, ...)
	/home/karl/go/src/github.com/Percona-Lab/mysql_random_data_load/main.go:273 +0x1f1
main.main()
	/home/karl/go/src/github.com/Percona-Lab/mysql_random_data_load/main.go:211 +0xa1a

**Comment by guriandoro** [comment]
Hi!

Can you please send the following additional information?
   - mysql_random_data_load version
   - mysql version
   - SHOW CREATE TABLE

**Comment by baiy01** [comment]
I have the same issue.
mysql_random_data_load version:0.1.10
mysql version:5.6.43  
SHOW CREATE TABLE:the same with sample
CREATE TABLE `test`.`t3` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tcol01` tinyint(4) DEFAULT NULL,
  `tcol02` smallint(6) DEFAULT NULL,
  `tcol03` mediumint(9) DEFAULT NULL,
  `tcol04` int(11) DEFAULT NULL,
  `tcol05` bigint(20) DEFAULT NULL,
  `tcol06` float DEFAULT NULL,
  `tcol07` double DEFAULT NULL,
  `tcol08` decimal(10,2) DEFAULT NULL,
  `tcol09` date DEFAULT NULL,
  `tcol10` datetime DEFAULT NULL,
  `tcol11` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tcol12` time DEFAULT NULL,
  `tcol13` year(4) DEFAULT NULL,
  `tcol14` varchar(100) DEFAULT NULL,
  `tcol15` char(2) DEFAULT NULL,
  `tcol16` blob,
  `tcol17` text,
  `tcol18` mediumtext,
  `tcol19` mediumblob,
  `tcol20` longblob,
  `tcol21` longtext,
  `tcol22` mediumtext,
  `tcol23` varchar(3) DEFAULT NULL,
  `tcol24` varbinary(10) DEFAULT NULL,
  `tcol25` enum('a','b','c') DEFAULT NULL,
  `tcol26` set('red','green','blue') DEFAULT NULL,
  `tcol27` float(5,3) DEFAULT NULL,
  `tcol28` double(4,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

**Comment by baiy01** [comment]
I tried other DLL,but same issue happened.
I use (Centos 7 x64) ,too

**Comment by timhughes** [comment]
Same issue

```
[root@ip-10-0-0-170 ~]# mysql_random_data_load --version xx xxx 2
Version   : v0.1.10
Commit    : 77ba5b493094d79318d941ea45f43268115c7be1
Branch    : master
Build     : 2018-10-10T16:39:41-0300
Go version: go1.11.1
```
```
[root@ip-10-0-0-170 ~]# rpm -qa|grep Percona
Percona-Server-client-57-5.7.27-30.1.el6.x86_64
Percona-Server-57-debuginfo-5.7.27-30.1.el6.x86_64
Percona-Server-shared-57-5.7.27-30.1.el6.x86_64
Percona-Server-server-57-5.7.27-30.1.el6.x86_64
```
```
[root@ip-10-0-0-170 ~]# mysql theswamp -e 'show create table position_snapshot_account_decimal'

CREATE TABLE `position_snapshot_account_decimal` (
  `datasource` int(11) NOT NULL,
  `snapshot_id` bigint(20) NOT NULL,
  `account_id` bigint(20) NOT NULL,
  `position` decimal(22,8) DEFAULT NULL,
  `margin_call_time` datetime DEFAULT NULL,
  `open_cost` decimal(20,5) DEFAULT NULL,
  `cumulative_cost` decimal(20,5) DEFAULT NULL,
  `realised_profit` decimal(20,5) DEFAULT NULL,
  `long_unfilled_quantity` decimal(20,8) DEFAULT NULL,
  `long_unfilled_cost` decimal(20,5) DEFAULT NULL,
  `short_unfilled_quantity` decimal(20,8) DEFAULT NULL,
  `short_unfilled_cost` decimal(20,5) DEFAULT NULL,
  `last_calculated_margin` decimal(20,5) DEFAULT NULL,
  `last_calculated_profit_and_loss` decimal(30,5) DEFAULT NULL,
  `delta_cumulative_cost` decimal(20,5) DEFAULT NULL,
  `last_client_money_unrealised_profit` decimal(20,5) DEFAULT NULL,
  `last_open_quantity` decimal(20,8) DEFAULT NULL,
  `last_open_cost` decimal(20,5) DEFAULT NULL,
  `open_quantity_at_last_valuation` decimal(20,8) DEFAULT NULL,
  `broker_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`snapshot_id`,`account_id`,`datasource`),
  KEY `datasource` (`datasource`,`snapshot_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 STATS_SAMPLE_PAGES=20
```

## Stack Trace
```[root@ip-10-0-0-170 ~]# mysql_random_data_load --no-progress --max-threads=1 --bulk-size=5000 theswamp position_snapshot_account_decimal 5
INFO[2019-10-10T13:38:24Z] Starting                                     
panic: invalid argument to Int63n

goroutine 1 [running]:
math/rand.(*Rand).Int63n(0xc0000bc180, 0x8000000000000000, 0x3fde54ffa5faea9c)
	/usr/local/go/src/math/rand/rand.go:111 +0x10d
math/rand.Int63n(0x8000000000000000, 0x305)
	/usr/local/go/src/math/rand/rand.go:319 +0x37
github.com/Percona-Lab/mysql_random_data_load/internal/getters.(*RandomDecimal).Value(0xc000218740, 0xc000362000, 0xc0003622ef)
	/home/karl/go/src/github.com/Percona-Lab/mysql_random_data_load/internal/getters/decimal.go:17 +0x85
github.com/Percona-Lab/mysql_random_data_load/internal/getters.(*RandomDecimal).String(0xc000218740, 0xc000362000, 0x305)
	/home/karl/go/src/github.com/Percona-Lab/mysql_random_data_load/internal/getters/decimal.go:22 +0x2f
github.com/Percona-Lab/mysql_random_data_load/internal/getters.(*RandomDecimal).Quote(0xc000218740, 0xc000360600, 0x2ed)
	/home/karl/go/src/github.com/Percona-Lab/mysql_random_data_load/internal/getters/decimal.go:26 +0x2b
main.run(0xc00014e0c0, 0xc00016a080, 0xc00019c180, 0xc000320000, 0xc000324000, 0x14, 0x20, 0x1, 0x5, 0x8502f8, ...)
	/home/karl/go/src/github.com/Percona-Lab/mysql_random_data_load/main.go:273 +0x1f1
main.main()
	/home/karl/go/src/github.com/Percona-Lab/mysql_random_data_load/main.go:211 +0xa1a
```

**Comment by percona-csalguero** [comment]
Fixed in https://github.com/Percona-Lab/mysql_random_data_load/releases/tag/v0.1.12
