### ISSUE TITLE
Add --print to enable printing commands instead of directly running them.

### ISSUE THREAD

**Issue by guriandoro** [Percona-Lab/mysql_random_data_load#8]
Instead of the tool generating and running the SQL commands needed to insert data, add a new flag that can instead print the queries needed to STDOUT (or file), without running them.

It should still need connection to the server to get table definitions.

**Comment by percona-csalguero** [comment]
Done in 0.1.7
https://github.com/Percona-Lab/mysql_random_data_load/releases/tag/0.1.7
